language: python
python:
  - '3.8'

before_script:
  - pip install -r requirements.txt
  - psql -c 'create database Plateforme_Pur_Beurre;' -U postgres

env: DJANGO_SETTINGS_MODULE="pur_beurre.settings.travis"

services:
  - postgresql

script:
  - python ./manage.py test product
