language: python
python:
  - '3.8'

addons:
  firefox: latest

env:
  global:
    - MOZ_HEADLESS=1
    - DJANGO_SETTINGS_MODULE="pur_beurre.settings.travis"

before_script:
  - pip install -r requirements.txt
  - psql -c 'create database Plateforme_Pur_Beurre;' -U postgres

services:
  - postgresql

script:
  - python ./manage.py test product
  - python ./manage.py test functional_test
