OOF_KEY_KEPT = ["product_name",
                "generic_name",
                # "brands",
                "brands_tags",
                # "categories",
                "categories_tags",
                # "origins ",
                # "origins_tags",
                # "stores",
                # "purchase_places",
                # "purchase_places_tags",
                # "labels",
                "labels_tags",
                "nova_group",
                # "nova_groups",
                "nutrition_grade_fr",
                # "nutrition-score-fr_100g",
                # "nutrition-score-uk_100g",
                # "carbon-footprint_100g",
                "image_url",
                "nutrient_levels",
                "url",
                ]

ORDER_BY = [
    ("name", "name"),
    ("nova", "nova"),
    ("nutri_score", "nutri_score"),
    ("label_score", "label_score")
]