# Generated by Django 3.1.1 on 2020-11-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('nova', models.IntegerField()),
                ('nutri_score', models.CharField(max_length=1)),
                ('label_score', models.IntegerField(default=0)),
                ('salt', models.CharField(max_length=500)),
                ('sugars', models.CharField(max_length=500)),
                ('saturated', models.CharField(max_length=500)),
                ('fat', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('image_url', models.CharField(max_length=500)),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='product.Category')),
                ('labels', models.ManyToManyField(blank=True, related_name='products', to='product.Label')),
                ('origins', models.ManyToManyField(blank=True, related_name='products', to='product.Origin')),
                ('stores', models.ManyToManyField(blank=True, related_name='products', to='product.Store')),
            ],
        ),
    ]
